name: automerge
on: 
  pull_request:
    branches: 
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        if: github.event.pull_request.head.ref == 'dev'
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
          MERGE_LABELS: "automated-pr"
          MERGE_METHOD: "merge"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "60000"