name: automerge
on: 
  pull_request:
    branches: 
      - main
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Espera a que todos los checks pasen
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          wait-interval: 10 # seconds
          check-name: "Auto PR, CI para proyecto React"
      - name: automerge
        if: github.event.pull_request.head.ref == 'dev'
        uses: pascalgn/automerge-action@v0.14.3
        env:
          GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
          MERGE_LABELS: "automated-pr"
          MERGE_METHOD: "merge"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "60000"